package cli

import (
	"flag"
	"fmt"
	"io"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/leonp92/golem/internal/bloat"
	"github.com/leonp92/golem/internal/blog"
	"github.com/leonp92/golem/internal/ticket"
)

func SetStep(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("ticket set-step", flag.ContinueOnError)
	fs.SetOutput(stderr)
	repo := fs.String("repo", ".", "target repo root")
	id := fs.String("ticket", "", "ticket id (required)")
	expectedLines := fs.Int("expected-lines", 0, "expected diff line count for the step about to start")
	if err := fs.Parse(args); err != nil {
		return 1
	}
	if *id == "" {
		fmt.Fprintln(stderr, "usage: golem ticket set-step --ticket <id> --expected-lines <n>")
		return 1
	}

	ticketDir := filepath.Join(*repo, ".golem", "tickets", *id)
	s, err := ticket.Load(ticketDir)
	if err != nil {
		fmt.Fprintf(stderr, "loading ticket %s: %v\n", *id, err)
		return 1
	}
	s.CurrentStepExpectedLines = *expectedLines
	if err := s.Save(ticketDir); err != nil {
		fmt.Fprintf(stderr, "saving ticket: %v\n", err)
		return 1
	}
	return 0
}

// fileStat is one file's added+deleted line count from `git show --numstat`.
type fileStat struct {
	path  string
	lines int
}

// countChangedLines sums added+deleted lines in a commit, excluding
// generated files (bloat.IsGenerated, or linguist-generated in
// .gitattributes) and binary files.
func countChangedLines(worktreePath, sha string) (int, error) {
	stats, err := commitNumstat(worktreePath, sha)
	if err != nil {
		return 0, err
	}
	generated, err := linguistGenerated(worktreePath, sha, stats)
	if err != nil {
		return 0, err
	}
	count := 0
	for _, s := range stats {
		if bloat.IsGenerated(s.path) || generated[s.path] {
			continue
		}
		count += s.lines
	}
	return count, nil
}

// commitNumstat parses `git show --numstat -z`. Records are
// "added\tdeleted\tpath\0", or for a rename "added\tdeleted\t\0old\0new\0".
// Binary files report "-" for both counts and contribute zero lines.
func commitNumstat(worktreePath, sha string) ([]fileStat, error) {
	cmd := exec.Command("git", "show", "--numstat", "-z", "--format=", sha)
	cmd.Dir = worktreePath
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git show --numstat %s: %w", sha, err)
	}
	fields := strings.Split(strings.TrimLeft(string(out), "\n"), "\x00")
	var stats []fileStat
	for i := 0; i < len(fields); i++ {
		parts := strings.SplitN(fields[i], "\t", 3)
		if len(parts) != 3 {
			continue
		}
		p := parts[2]
		if p == "" && i+2 < len(fields) {
			p = fields[i+2] // rename: take the destination path
			i += 2
		}
		added, _ := strconv.Atoi(parts[0])
		deleted, _ := strconv.Atoi(parts[1])
		stats = append(stats, fileStat{path: p, lines: added + deleted})
	}
	return stats, nil
}

// linguistGenerated returns the paths marked linguist-generated by the
// .gitattributes in effect at sha.
func linguistGenerated(worktreePath, sha string, stats []fileStat) (map[string]bool, error) {
	if len(stats) == 0 {
		return map[string]bool{}, nil
	}
	paths := make([]string, len(stats))
	for i, s := range stats {
		paths[i] = s.path
	}
	cmd := exec.Command("git", "check-attr", "-z", "--source", sha, "--stdin", "linguist-generated")
	cmd.Dir = worktreePath
	cmd.Stdin = strings.NewReader(strings.Join(paths, "\x00") + "\x00")
	out, err := cmd.Output()
	if err != nil {
		return nil, fmt.Errorf("git check-attr: %w", err)
	}
	// Output records are "path\0attr\0value\0".
	fields := strings.Split(string(out), "\x00")
	generated := map[string]bool{}
	for i := 0; i+2 < len(fields); i += 3 {
		if v := fields[i+2]; v == "set" || v == "true" {
			generated[fields[i]] = true
		}
	}
	return generated, nil
}

func commitDiff(worktreePath, sha string) (string, error) {
	cmd := exec.Command("git", "show", sha)
	cmd.Dir = worktreePath
	out, err := cmd.Output()
	return string(out), err
}

func CheckBloat(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("ticket check-bloat", flag.ContinueOnError)
	fs.SetOutput(stderr)
	repo := fs.String("repo", ".", "target repo root")
	id := fs.String("ticket", "", "ticket id (required)")
	commit := fs.String("commit", "", "commit SHA to check (required)")
	if err := fs.Parse(args); err != nil {
		return 1
	}
	if *id == "" || *commit == "" {
		fmt.Fprintln(stderr, "usage: golem ticket check-bloat --ticket <id> --commit <sha>")
		return 1
	}

	ticketDir := filepath.Join(*repo, ".golem", "tickets", *id)
	s, err := ticket.Load(ticketDir)
	if err != nil {
		fmt.Fprintf(stderr, "loading ticket %s: %v\n", *id, err)
		return 1
	}

	actual, err := countChangedLines(s.WorktreePath, *commit)
	if err != nil {
		fmt.Fprintf(stderr, "counting changed lines: %v\n", err)
		return 1
	}

	exceeded, ratio := bloat.Check(actual, s.CurrentStepExpectedLines)
	if !exceeded {
		return 0
	}

	w, err := blog.NewWriter(filepath.Join(ticketDir, "log.jsonl"))
	if err != nil {
		fmt.Fprintf(stderr, "opening log: %v\n", err)
		return 1
	}
	defer closeLogWriter(w, stderr)
	e := blog.NewEntry("system", blog.TypeFinding, fmt.Sprintf(
		"SCOPE_BLOAT: commit changed %d lines against a %d-line expectation (%.1fx)",
		actual, s.CurrentStepExpectedLines, ratio))
	e.CommitSHA = *commit
	if err := w.Append(e); err != nil {
		fmt.Fprintf(stderr, "writing finding: %v\n", err)
		return 1
	}
	return 0
}
